name: "Deploy Release"

on:
  push:
    tags:
    - '*'

jobs:
  release:
    name: Deploy release
    runs-on: "ubuntu-latest"
    container: "marijnstevens/yagna-aarch64-build-system"

    steps:
      - run: "curl https://sh.rustup.rs -sSf | sh -s -- -y"      
      
      - run: 'echo "/__w/_temp/_github_home/.cargo/bin/" >> $GITHUB_PATH'
         
      - run: "rustup target install aarch64-unknown-linux-gnu"
      
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Stamp latest tag
        uses: EndBug/latest-tag@latest
        with:
          description: Update latest tag.

      - run: ./init-submodules.sh

      - name: "yagna"
        run: ./build.sh yagna

      - name: "ya-runtime-vm"
        run: ./build.sh ya-runtime-vm

      - name: "ya-runtime-wasi"
        run: ./build.sh ya-runtime-wasi

      - run: ./build-release-artifact.sh

      - uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body: ""
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: yagna.tar.gz
          asset_name: yagna.tar.gz
          asset_content_type: application/gzip

